FROM debian:12

# Set environment variables if you're using a proxy server
# ENV http_proxy=http://your-proxy-server:port
# ENV https_proxy=http://your-proxy-server:port

RUN apt update -y && apt install curl -y

RUN echo "deb [trusted=yes] http://192.168.1.100:8080/debian/debian stable main" > /etc/apt/sources.list \
    && rm -f /etc/apt/sources.list.d/debian.sources \
    && apt-get update -y \
    && apt-get install emacs -y
