name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build
        run: go build -o gobinrepo ./cmd/gobinrepo

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: gobinrepo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
